CREATE TABLE USUARIOS (
    ID            NUMBER PRIMARY KEY,
    NOME          VARCHAR2(100) NOT NULL,
    EMAIL         VARCHAR2(150) NOT NULL,
    PRIORIDADE    NUMBER(2) CHECK (PRIORIDADE BETWEEN 1 AND 3),
    SALDO         NUMBER(10,2) DEFAULT 0,
    TRUST_SCORE   NUMBER DEFAULT 100
);

CREATE TABLE INSCRICOES (
    ID            NUMBER PRIMARY KEY,
    USUARIO_ID    NUMBER NOT NULL,
    STATUS        VARCHAR2(20),
    VALOR_PAGO    NUMBER(10,2),
    TIPO          VARCHAR2(50),

    CONSTRAINT FK_USUARIO
        FOREIGN KEY (USUARIO_ID)
        REFERENCES USUARIOS(ID)
);

CREATE TABLE LOG_AUDITORIA (
    ID              NUMBER PRIMARY KEY,
    INSCRICAO_ID    NUMBER,
    MOTIVO          VARCHAR2(255),
    DATA            DATE,

    CONSTRAINT FK_INSCRICAO
        FOREIGN KEY (INSCRICAO_ID)
        REFERENCES INSCRICOES(ID)
);

CREATE SEQUENCE USUARIOS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE INSCRICOES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LOG_AUDITORIA_SEQ START WITH 1 INCREMENT BY 1;