INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Joao', 'joao@gmail.com', 2, 100, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Bot1', 'bot@fake.com', 1, 50, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Bot2', 'hacker@temp-mail.com', 1, 30, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Maria', 'maria@email.com', 3, 200, 100);

INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 1, 'PENDING', 100, 'VIP');
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 2, 'PENDING', 50, 'NORMAL');
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 3, 'PENDING', 30, 'NORMAL');
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 4, 'CONFIRMED', 200, 'VIP');

COMMIT;
