-- USUARIOS
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Joao', 'joao@gmail.com', 2, 100, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Bot1', 'bot@fake.com', 1, 50, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Bot2', 'hacker@temp-mail.com', 1, 30, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Maria', 'maria@email.com', 3, 200, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Carlos', 'carlos@gmail.com', 2, 120, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Ana', 'ana@fake.com', 1, 80, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Pedro', 'pedro@temp-mail.com', 1, 60, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Lucas', 'lucasemail.com', 2, 90, 100); -- malformado
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Julia', 'julia@empresa.com', 3, 150, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Marcos', 'marcos@fake.com', 1, 40, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Fernanda', 'fernanda@outlook.com', 2, 110, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Roberto', 'roberto@temp-mail.com', 1, 70, 100);
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Patricia', 'patricia@email', 2, 95, 100); -- malformado
INSERT INTO USUARIOS VALUES (USUARIOS_SEQ.NEXTVAL, 'Bruno', 'bruno@gmail.com', 2, 130, 100);

-- INSCRICOES
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 2, 'PENDING', 50, 'NORMAL');
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 3, 'PENDING', 30, 'NORMAL');
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 4, 'CONFIRMED', 200, 'VIP');
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 5, 'PENDING', 120, 'NORMAL');
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 6, 'PENDING', 80, 'NORMAL'); -- fake.com
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 7, 'PENDING', 60, 'NORMAL'); -- temp-mail
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 8, 'PENDING', 90, 'VIP');    -- malformado
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 9, 'CONFIRMED', 150, 'VIP');
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 10, 'PENDING', 40, 'NORMAL'); -- fake.com
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 11, 'PENDING', 110, 'VIP');
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 12, 'PENDING', 70, 'NORMAL'); -- temp-mail
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 13, 'PENDING', 95, 'NORMAL'); -- malformado
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 14, 'CANCELLED', 130, 'VIP');
INSERT INTO INSCRICOES VALUES (INSCRICOES_SEQ.NEXTVAL, 1, 'PENDING', 100, 'VIP');


COMMIT;